---
title: "Tidy Tuesday Pokemon"
author: "Alex Copeland"
format: 
    html:
        embed-resources: true
editor: visual
---

## Load Data Set
```{R}
pokemon_df_old<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-01/pokemon_df.csv', show_col_types = FALSE)
```

## Dataset

This week we are exploring Pokemon! This dataset is sourced from {pokemon} (CRAN \| github), an R package which provides Pokemon information in both English and Brazilian Portuguese.

## Simulation

```{r}

# Making new df
pokemon_df <- pokemon_df_old[, (c("pokemon", "hp", "attack", "defense", "special_attack", "special_defense", "speed"))]
```

```{R}
#Setting Seed for simulation
set.seed(1)

```



```{R}
#Define Score to be all of the pokemons' stats summed.

pokemon_df$score <- pokemon_df_old$hp + 
                    pokemon_df_old$attack + 
                    pokemon_df_old$defense + 
                    pokemon_df_old$special_attack + 
                    pokemon_df_old$special_defense + 
                    pokemon_df_old$speed
```



```{r}
fight_sim <- function(pokemon1, pokemon2, sigma, iterations = 10) {

  wins_pokemon1 <- 0
  wins_pokemon2 <- 0
  ties <- 0

    for (k in 1:iterations) {
      
      # Defining a random number +- of sigma to be luck factor.
      epsilon_a <- runif(1, -sigma, sigma)
      epsilon_b <- runif(1, -sigma, sigma)
  
      # Updating new score
      score_pokemon1 <- pokemon1$score + epsilon_a
      score_pokemon2 <- pokemon2$score + epsilon_b
      
        #Logic
        if (score_pokemon1 > score_pokemon2) {
          wins_pokemon1 <- wins_pokemon1 + 1
        }
        else if (score_pokemon2 > score_pokemon1) {
           wins_pokemon2 <- wins_pokemon2 + 1
        }
        else {
            ties <- ties + 1
        }
    }
  
    win_loss_pokemon <- data.frame(
      pokemon1 = pokemon1$pokemon[1],
      pokemon2 = pokemon2$pokemon[1],
      wins_pokemon1 = wins_pokemon1,
      wins_pokemon2 = wins_pokemon2,
      ties = ties
    )
    return(win_loss_pokemon)
}

```



```{R}
#Define noise for simulation

# We define sigma, to control amount of luck in simulation.
sigma <- 50

# Define total iterations and counter for pb
total_iterations <- choose(nrow(pokemon_df),2)
counter <- 0

# Define progress bar
pb <- txtProgressBar(min = 0, max = total_iterations, style = 3)

# Define an emtpy df to rbind with in loop.
total_win_loss_pokemon <- data.frame()
  for (i in 1:nrow(pokemon_df)){
  if (i == nrow(pokemon_df)){
    break
    }
  for (j in (i + 1):nrow(pokemon_df)){
      # Start time
      start <- Sys.time()
      # Save fight sim in a var, so the returned result in fn can be rbind with.
      pokemon_fight <- fight_sim(pokemon_df[i,], pokemon_df[j,], sigma)
      # rbind with itself and the results of the sim.
      total_win_loss_pokemon <- rbind(total_win_loss_pokemon, pokemon_fight)
      
      # Progress Bar
      counter <- counter + 1
      setTxtProgressBar(pb, counter)
      }
  }
```

```{R}

# Output csv
write.csv(total_win_loss_pokemon,
          file = "pokemon_tournament_results.csv",
          row.names = FALSE)

```








